-- Migration: Create variacoes table
-- Description: Stores product variations such as size, color, kit, or price-specific options
-- Date: 2026-05-08

CREATE TABLE IF NOT EXISTS variacoes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	produto_id BIGINT NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
	nome TEXT NOT NULL,
	preco NUMERIC NULL,
	estoque INTEGER NOT NULL DEFAULT 0,
	ordem INTEGER NOT NULL DEFAULT 0,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT variacoes_produto_nome_unique UNIQUE (produto_id, nome)
);

CREATE INDEX IF NOT EXISTS idx_variacoes_produto_id
	ON variacoes (produto_id);

CREATE INDEX IF NOT EXISTS idx_variacoes_produto_ativo_ordem
	ON variacoes (produto_id, ativo, ordem);

ALTER TABLE variacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_public_read_variacoes" ON variacoes;
CREATE POLICY "allow_public_read_variacoes"
	ON variacoes
	FOR SELECT
	USING (true);

GRANT SELECT ON TABLE variacoes TO anon, authenticated;
